# Generated by Django 5.2 on 2026-07-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_palestrantecoin_patrocinadorcoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(max_length=550, verbose_name='Resumo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hackathon/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link do site do Hackathon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Hackathon CoIn',
                'verbose_name_plural': 'Hackathons CoIn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='palestrantecoin',
            name='description',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
    ]
